server:
  port: 5000
  servlet:
    context-path: /

spring:
  application:
    name: user-service-local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, h2-console
